{
 "title": "UPS statistics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "ups",
    "label": "UPS",
    "query": {
     "query": "label_values(network_ups_tools_device_info, ups)"
    }
   }
  ]
 },
 "panels": [
  { "title": "设备状态", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "UPS 状态",
   "type": "stat",
   "description": " * OL - On line (mains is present)\n * OB - On battery (mains is not present)\n * LB - Low battery\n * HB - High battery\n * RB - The battery needs to be replaced\n * CHRG - The battery is charging\n * DISCHRG - The battery is discharging (inverter is providing load power)\n * BYPASS - UPS bypass circuit is active -- no battery protection is available\n * CAL - UPS is currently performing runtime calibration (on battery)\n * OFF - UPS is offline and is not supplying power to the load\n * OVER - UPS is overloaded\n * TRIM - UPS is trimming incoming voltage (called \"buck\" in some hardware)\n * BOOST - UPS is boosting incoming voltage\n * FSD and SD - Forced Shutdown",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_status == 1",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "电池电量",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_charge{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "电池电压",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{ups=\"$ups\"}",
     "legendFormat": "电池电压"
    }
   ]
  },
  {
   "title": "输入电压",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{ups=\"$ups\"}",
     "legendFormat": "当前电压"
    }
   ]
  },
  {
   "title": "制造商",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{ups=\"$ups\"}",
     "legendFormat": "{{mfr}}"
    }
   ]
  },
  {
   "title": "电池可用时间",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}"
    }
   ]
  },
  {
   "title": "型号",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "network_ups_tools_device_info{ups=\"$ups\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "UPS信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "UPS 信息",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      { "expr": "network_ups_tools_ups_info" }
     ]
    },
    {
     "title": "设备信息",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      { "expr": "network_ups_tools_device_info" }
     ]
    },
    {
     "title": "电池信息",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      { "expr": "network_ups_tools_battery_info" }
     ]
    },
    {
     "title": "驱动信息",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      { "expr": "network_ups_tools_driver_info" }
     ]
    }
   ]
  },
  {
   "title": "状态信息",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "负载",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "network_ups_tools_ups_load{ups=\"$ups\"}",
     "legendFormat": "负载"
    }
   ]
  },
  {
   "title": "预计可用时间",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_runtime{ups=\"$ups\"}",
     "legendFormat": "预计可用时间"
    }
   ]
  },
  {
   "title": "输入电压",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_input_voltage{ups=\"$ups\"}",
     "legendFormat": "输入电压"
    }
   ]
  },
  {
   "title": "电池电压",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "network_ups_tools_battery_voltage{ups=\"$ups\"}",
     "legendFormat": "电池电压"
    }
   ]
  }
 ]
}